create table if not exists player_stats (
    user_name TEXT PRIMARY KEY,
    played_games INT DEFAULT 0,
    words_per_min_avg NUMERIC DEFAULT 0
);

create table if not exists game_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name TEXT NOT NULL,
    words_per_min INT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

create or replace function update_player_stats()
returns trigger as $$
begin
    insert into player_stats (user_name, played_games, words_per_min_avg)
    values (new.user_name, 0, 0)
    on conflict (user_name) do nothing;

    update player_stats
    set 
        played_games = (select count(*) from game_results where user_name = new.user_name),
        words_per_min_avg = (select avg(words_per_min) from game_results where user_name = new.user_name)
    where user_name = new.user_name;

    return new;
end;
$$ language plpgsql;

drop trigger if exists on_game_result_insert on game_results;
create trigger on_game_result_insert
after insert on game_results
for each row
execute function update_player_stats();

